### ISSUE TITLE
Server gets stuck on polling

### ISSUE THREAD

**Issue by gagangoel1994** [rams3sh/cowin4all#20]
I came across this repo today, wanted to give it a try. Everything seems to work fine, but after 10-12 polls the app server seems to get stuck. FYI, I have done the setup on windows using anaconda.

Here are the logs - https://pastebin.com/FcL5K6W8

**Comment by rams3sh** [comment]
Hey @gagangoel1994 

Can you pull the code from develop branch. 

Use the following command :- 

```
pip3 uninstall cowin4all    # To uninstall previous version
pip3 install git+https://github.com/rams3sh/cowin4all.git@develop  # Install new code committed as part of develop branch
```

I have added read time out to the request now. Let me know if it works for you !! 

There was long pending issue about handling the ReadTimeout. Sometime CoWIN delays the response because of which the app keeps waiting for the response to come. If you would have waited for 5 minutes (thats the exact time that CoWIN make the requester wait) , you would have seen it resuming 😛 !! Never the less , now it should throw the exception and re try the request !!

**Comment by gagangoel1994** [comment]
It's working now, Thanks for the quick resolution :)
